Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2020-05, with the labels that each got.

#20 Make CRDs v1.11 compatible
  charts/gardener-extension-shoot-cert-service/templates/crds.yaml
  charts/internal/shoot-cert-management-shoot/templates/crds.yaml
  example/controller-registration.yaml
Labels: kind/bug, needs/ok-to-test

#21 Vendor gardener/gardener@v1.4.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: needs/ok-to-test

#22 remove lastPendingTimestamp as required field in status
  charts/internal/shoot-cert-management-shoot/templates/crds.yaml
Labels: needs/ok-to-test, reviewed/lgtm
