Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2020-10, with the labels that each got.

#38 Enhance chart options
  Dockerfile
  charts/gardener-extension-shoot-cert-service/templates/deployment.yaml
  charts/gardener-extension-shoot-cert-service/templates/vpa.yaml
  charts/gardener-extension-shoot-cert-service/values.yaml
  example/controller-registration.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm, size/s

#40 Add PropagationTimeout option
  charts/gardener-extension-shoot-cert-service/values.yaml
  charts/internal/shoot-cert-management-seed/templates/deployment.yaml
  charts/internal/shoot-cert-management-seed/values.yaml
  example/00-config.yaml
  example/controller-registration.yaml
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/controller/actuator.go
Labels: area/control-plane, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#41 add priority class for extension pods
  charts/gardener-extension-shoot-cert-service/templates/_helpers.tpl
  charts/gardener-extension-shoot-cert-service/templates/deployment.yaml
  charts/gardener-extension-shoot-cert-service/templates/priorityclass.yaml
  example/controller-registration.yaml
Labels: area/high-availability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#42 Add missing propagationTimeout to Helm chart
  charts/gardener-extension-shoot-cert-service/templates/_helpers.tpl
  example/controller-registration.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs
