Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2020-07, with the labels that each got.

#29 Fix nil pointer when spec.providerConfig=nil
  pkg/controller/actuator.go
Labels: needs/ok-to-test, reviewed/lgtm

#30 Avoid unnecessary nil checks
  hack/api-reference/service.md
  pkg/apis/service/types.go
  pkg/apis/service/v1alpha1/types.go
  pkg/controller/actuator.go
Labels: needs/ok-to-test, reviewed/lgtm

#32 [ci:component:github.com/gardener/cert-management:v0.3.0->v0.3.1]
  charts/images.yaml
Labels: needs/ok-to-test

#31 Fix cert-controller-manager leader election
  charts/internal/shoot-cert-management-seed/templates/deployment.yaml
  charts/internal/shoot-cert-management-shoot/templates/cert-management-role.yaml
  charts/internal/shoot-cert-management-shoot/templates/cert-management-rolebinding.yaml
  pkg/controller/actuator.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm
