Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2020-06, with the labels that each got.

#25 Remove lastPendingTimestamp from CRD
  charts/internal/shoot-cert-management-shoot/templates/crds.yaml
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#26 updated to cert-management v0.2.16
  charts/images.yaml
  charts/internal/shoot-cert-management-shoot/templates/crds.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#27 Fix netpol label for cert-management
  charts/internal/shoot-cert-management-seed/templates/deployment.yaml
Labels: area/networking, needs/ok-to-test, priority/critical, reviewed/lgtm
