Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2021-06, with the labels that each got.

#75 Fix certmanagerParser bug
  charts/gardener-extension-shoot-cert-service/templates/configmap-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#77 fix component descriptor script
  .ci/component_descriptor
Labels: needs/ok-to-test, needs/review, size/xs

#78 Update README.md
  README.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#80 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
