Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2021-12, with the labels that each got.

#101 Add permissions to watch dnsrecords.extensions.gardener.cloud
  charts/gardener-extension-shoot-cert-service/templates/rbac.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, area/quality, kind/bug, reviewed/lgtm, size/xs

#102 Remove unneeded permissions
  charts/gardener-extension-shoot-cert-service/templates/rbac.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, area/control-plane, kind/technical-debt, needs/review, size/xs

#104 Remove the "garden.sapcloud.io/role" label from control plane components
  charts/internal/shoot-cert-management-seed/templates/deployment.yaml
Labels: needs/ok-to-test, kind/cleanup, reviewed/lgtm, size/xs
