Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2022-07, with the labels that each got.

#125 No predefined resources
  charts/gardener-extension-shoot-cert-service/values.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#126 Adapt the priority according to the gardener guideline
  charts/gardener-extension-shoot-cert-service/templates/_helpers.tpl
  charts/gardener-extension-shoot-cert-service/templates/deployment.yaml
  charts/gardener-extension-shoot-cert-service/templates/priorityclass.yaml
  charts/internal/shoot-cert-management-seed/templates/deployment.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, area/quality, kind/enhancement, reviewed/lgtm, size/xs

#127 Refactoring certificate documentation
  .gitignore
  docs/usage/custom_shoot_issuer.md
  docs/usage/request_cert.md
  docs/usage/request_default_domain_cert.md
Labels: needs/ok-to-test, area/documentation, kind/enhancement, reviewed/lgtm, size/xl
