Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2022-06, with the labels that each got.

#119 Support issuer specific precheck nameservers
  charts/gardener-extension-shoot-cert-service/templates/crds.yaml
  charts/internal/shoot-cert-management-seed/templates/ca-certificats-configmap.yaml
  charts/internal/shoot-cert-management-seed/templates/deployment.yaml
  charts/internal/shoot-cert-management-seed/templates/issuer.yaml
  charts/internal/shoot-cert-management-shoot/templates/crds-v1.yaml
  charts/internal/shoot-cert-management-shoot/templates/crds-v1beta1.yaml
  docs/usage/request_cert.md
  example/20-crd-issuer.yaml
  example/30-extension.yaml
  example/controller-registration.yaml
  hack/api-reference/service.md
  pkg/apis/service/types.go
  pkg/apis/service/v1alpha1/types.go
  pkg/apis/service/v1alpha1/zz_generated.conversion.go
  pkg/apis/service/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/service/validation/validation.go
  pkg/apis/service/validation/validation_test.go
  pkg/apis/service/zz_generated.deepcopy.go
  pkg/controller/actuator.go
Labels: needs/ok-to-test, area/control-plane, kind/api-change, kind/enhancement, reviewed/lgtm, size/m

#121 Change base image from alpine to distroless
  Dockerfile
Labels: needs/ok-to-test, area/open-source, area/security, kind/enhancement, needs/changes, needs/review, size/xs

#122 Adjust metric name due to upgrading the kube-state-metrics component
  charts/internal/shoot-cert-management-seed/cert-dashboard.json
Labels: needs/ok-to-test, area/monitoring, kind/enhancement, reviewed/lgtm, size/xs
