Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2023-07, with the labels that each got.

#170 Introduce persona-based docs
  .docforge/manifest.yaml
  docs/operations/deployment.md
  docs/tutorials/images/access.png
  docs/tutorials/images/k9s.png
  docs/tutorials/tutorial-custom-domain-with-istio.md
Labels: needs/ok-to-test, kind/cleanup, needs/review, size/s

#172 Improve docu for custom/shoot issuers
  docs/usage/custom_shoot_issuer.md
  docs/usage/request_cert.md
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/s

#174 add certificate expiration alert
  charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml
  charts/internal/shoot-cert-management-seed/values.yaml
Labels: needs/ok-to-test, area/monitoring, kind/enhancement, reviewed/lgtm, size/xs

#176 Add configuration field for alerting days
  charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml
  docs/usage/alerting.md
  example/30-extension.yaml
  hack/api-reference/service.md
  pkg/apis/service/types.go
  pkg/apis/service/v1alpha1/types.go
  pkg/apis/service/v1alpha1/zz_generated.conversion.go
  pkg/apis/service/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/service/zz_generated.deepcopy.go
  pkg/controller/actuator.go
Labels: reviewed/ok-to-test, needs/ok-to-test, area/control-plane, kind/api-change, kind/enhancement, reviewed/lgtm, size/m
