Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2023-08, with the labels that each got.

#177 Add dependabot to manage gardener packages
  .github/dependabot.yaml
  .github/workflows/vendor_gardener.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/s

#181 Refactor imagevector package to conform to usage pattern in gardener/gardener
  .dockerignore
  charts/charts.go
  imagevector/images.yaml
  imagevector/imagevector.go
  pkg/controller/actuator.go
Labels: reviewed/ok-to-test, needs/ok-to-test, area/dev-productivity, kind/enhancement, reviewed/lgtm, size/xs

#184 Drop last usage of `github.com/golang/mock`
  go.mod
  go.sum
  hack/tools.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/mockgen/mockgen.go
  vendor/github.com/golang/mock/mockgen/model/model.go
  vendor/github.com/golang/mock/mockgen/parse.go
  vendor/github.com/golang/mock/mockgen/reflect.go
  vendor/github.com/golang/mock/mockgen/version.1.11.go
  vendor/github.com/golang/mock/mockgen/version.1.12.go
  vendor/modules.txt
Labels: needs/ok-to-test, kind/cleanup, reviewed/lgtm, size/xs

#188 Add docu for preferred chain
  docs/usage/request_cert.md
  docs/usage/request_default_domain_cert.md
Labels: reviewed/ok-to-test, needs/ok-to-test, area/documentation, kind/enhancement, reviewed/lgtm, size/s

#189 Revert to v1.36.0-dev because of failed release build completion
  VERSION
  example/controller-registration.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/xs

#190 No alerting for certificates in error state
  charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, area/monitoring, kind/bug, reviewed/lgtm, size/xs
