Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2023-03, with the labels that each got.

#149 Remove minAllowed.cpu for all components
  charts/gardener-extension-shoot-cert-service/templates/vpa.yaml
  charts/gardener-extension-shoot-cert-service/values.yaml
  charts/internal/shoot-cert-management-seed/templates/vpa.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, reviewed/lgtm, size/xs, area/os, area/auto-scaling

#150 Fix an error in the charts
  charts/gardener-extension-shoot-cert-service/templates/deployment.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, kind/bug, needs/review, size/xs

#152 Adapt `NetworkPolicy` rules according to recent refactorings
  charts/gardener-extension-shoot-cert-service/templates/deployment.yaml
  charts/gardener-extension-shoot-cert-service/templates/service.yaml
  charts/internal/shoot-cert-management-seed/templates/deployment.yaml
  charts/internal/shoot-cert-management-seed/templates/service.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, area/dev-productivity, area/networking, area/ops-productivity, area/security, kind/enhancement, reviewed/lgtm, size/s

#153 bump builder image to golang:1.20.2
  Dockerfile
  go.mod
Labels: needs/ok-to-test, needs/review, size/xs

#154 Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  go.mod
  go.sum
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: needs/ok-to-test, area/control-plane, kind/bug, reviewed/lgtm, size/xs

#156 [release-v1.30] Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  go.mod
  go.sum
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: needs/ok-to-test, area/control-plane, kind/bug, needs/review, size/xs

#158 Add secretLabels section to certificates CRD
  charts/internal/shoot-cert-management-shoot/templates/crds-v1.yaml
  docs/usage/request_cert.md
  docs/usage/request_default_domain_cert.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
