Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2023-06, with the labels that each got.

#165 Fixed broken links - 2023.06
  docs/tutorial-custom-domain-with-istio.md
Labels: needs/ok-to-test, area/documentation, kind/enhancement, reviewed/lgtm, size/xs

#168 Remove old and obsolete logging configuration
  charts/gardener-extension-shoot-cert-service/templates/clusterfilters-logging.yaml
  charts/gardener-extension-shoot-cert-service/templates/clusterparsers-logging.yaml
  charts/gardener-extension-shoot-cert-service/templates/configmap-logging.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, area/logging, kind/cleanup, reviewed/lgtm, size/s

#166 Add dashboard panel for certificate object expire date
  Dockerfile
  charts/internal/shoot-cert-management-seed/cert-dashboard.json
Labels: needs/ok-to-test, needs/review, size/s
