Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2023-01, with the labels that each got.

#139 Drop support for kubernetes < 1.20 for shoot cert service extension
  charts/gardener-extension-shoot-cert-service/templates/rbac-shoot-cert-service.yaml
  charts/internal/shoot-cert-management-shoot/values.yaml
  docs/tutorial-custom-domain-with-istio.md
  example/10-fake-shoot-controlplane.yaml
  example/30-cluster.yaml
  example/controller-registration.yaml
  hack/api-reference/config.json
  hack/api-reference/config.md
  hack/api-reference/service.json
  pkg/controller/actuator.go
Labels: needs/ok-to-test, area/open-source, kind/cleanup, reviewed/lgtm, size/m

#140 Add Fluent Operator resources
  charts/gardener-extension-shoot-cert-service/templates/clusterfilters-logging.yaml
  charts/gardener-extension-shoot-cert-service/templates/clusterparsers-logging.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, area/logging, kind/enhancement, reviewed/lgtm, size/s

#141 Update builder image to golang:1.19.5
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs
