Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2023-05, with the labels that each got.

#160 Update request_cert.md
  docs/usage/request_cert.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#162 bump golang:1.20.4
  Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#163 Adapt `NetworkPolicy`s
  charts/gardener-extension-shoot-cert-service/templates/service.yaml
  charts/internal/shoot-cert-management-seed/templates/service.yaml
  example/controller-registration.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, area/networking, area/security, kind/enhancement, reviewed/lgtm, size/xs
