Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2024-11, with the labels that each got.

#312 chore: Remove obsolete Make target adjust-install-gosec.sh
  Makefile
Labels: needs/ok-to-test, area/quality, kind/cleanup, needs/review, size/xs

#318 Vertical scaling on CPU dropped in VPA resource
  charts/internal/shoot-cert-management-seed/templates/vpa.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, area/control-plane, kind/task, reviewed/lgtm, size/xs

#322 chore: Refresh cert-management CRDs
  charts/internal/shoot-cert-management-shoot/templates/crds-v1.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, area/control-plane, kind/task, reviewed/lgtm, size/l
