Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2025-07, with the labels that each got.

#422 Add annotation `cert.gardener.cloud/class` for control plane issuers
  pkg/controller/extension/shared/deployer_issuers.go
  pkg/controller/extension/shared/deployer_test.go
Labels: area/control-plane, kind/enhancement, size/S, cla: yes, lgtm, approved

#434 REUSE: Convert DEP5 to `REUSE.toml`
  .reuse/dep5
  REUSE.toml
Labels: area/open-source, kind/enhancement, size/M, cla: yes, lgtm, approved

#435 chore: Update cert-management to v0.17.8
  go.mod
  go.sum
  pkg/controller/extension/shared/assets/crd-cert.gardener.cloud_certificates.yaml
Labels: area/open-source, kind/task, size/M, cla: yes, lgtm, approved

#437 Drop support for Shoots with Kubernetes version <= 1.28
  docs/tutorials/tutorial-custom-domain-with-istio.md
  example/10-fake-shoot-controlplane.yaml
  example/30-cluster.yaml
  hack/api-reference/config.json
  hack/api-reference/config.md
  hack/api-reference/service.json
  renovate.json5
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved
