Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2025-08, with the labels that each got.

#452 chore: Group Go Renovate updates
  renovate.json5
Labels: area/dev-productivity, kind/enhancement, size/S, cla: yes, lgtm, approved, reviewed/ok-to-test

#453 Update the build badge from Concourse to GitHub Actions
  README.md
Labels: area/delivery, kind/cleanup, size/XS, cla: yes, lgtm, approved

#455 chore: Use Renovate preset for grouping Go updates
  renovate.json5
Labels: area/dev-productivity, kind/enhancement, size/S, cla: yes, lgtm, approved, reviewed/ok-to-test

#459 Harmonize `Extension` generation
  .gitignore
  Makefile
  docs/operations/deployment.md
  example/doc.go
  example/extension.yaml
  example/extension/base/extension-patch.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/extension.yaml
  example/extension/kustomization.yaml
  example/shoot-cert-service/base/doc.go
  example/shoot-cert-service/base/kustomization.yaml
  example/shoot-cert-service/example/extension-patch.yaml
  hack/pebble-up.sh
  hack/prepare-operator-extension.sh
  skaffold.yaml
Labels: area/ops-productivity, kind/cleanup, size/L, cla: yes, lgtm, approved, reviewed/ok-to-test
