Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2025-04, with the labels that each got.

#365 Address TODO for legacy NetworkPolicy labels
  charts/gardener-extension-shoot-cert-service/templates/service.yaml
  charts/internal/shoot-cert-management-seed/templates/service.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, area/quality, kind/cleanup, needs/review, size/xs

#366 Switch Slack references to Gardener workspace
  README.md
Labels: needs/ok-to-test, area/open-source, kind/enhancement, reviewed/lgtm, size/xs

#357 Deploy cert-management using Go code instead of charts
  Makefile
  charts/charts.go
  charts/gardener-extension-shoot-cert-service/templates/_helpers.tpl
  charts/gardener-extension-shoot-cert-service/templates/deployment.yaml
  charts/gardener-extension-shoot-cert-service/templates/rbac.yaml
  charts/gardener-extension-shoot-cert-service/values.yaml
  charts/internal/shoot-cert-management-seed/.helmignore
  charts/internal/shoot-cert-management-seed/Chart.yaml
  charts/internal/shoot-cert-management-seed/templates/0helpers.tpl
  charts/internal/shoot-cert-management-seed/templates/ca-certificats-configmap.yaml
  charts/internal/shoot-cert-management-seed/templates/configmap-dashboards.yaml
  charts/internal/shoot-cert-management-seed/templates/deployment.yaml
  charts/internal/shoot-cert-management-seed/templates/issuer.yaml
  charts/internal/shoot-cert-management-seed/templates/poddisruptionbudget.yaml
  charts/internal/shoot-cert-management-seed/templates/prometheusrule.yaml
  charts/internal/shoot-cert-management-seed/templates/rbac.yaml
  charts/internal/shoot-cert-management-seed/templates/service.yaml
  charts/internal/shoot-cert-management-seed/templates/serviceaccount.yaml
  charts/internal/shoot-cert-management-seed/templates/servicemonitor.yaml
  charts/internal/shoot-cert-management-seed/templates/vpa.yaml
  charts/internal/shoot-cert-management-seed/values.yaml
  charts/internal/shoot-cert-management-shoot/Chart.yaml
  charts/internal/shoot-cert-management-shoot/templates/cert-management-role.yaml
  charts/internal/shoot-cert-management-shoot/templates/cert-management-rolebinding.yaml
  charts/internal/shoot-cert-management-shoot/templates/crds-v1.yaml
  charts/internal/shoot-cert-management-shoot/templates/rbac.yaml
  charts/internal/shoot-cert-management-shoot/values.yaml
  cmd/gardener-extension-shoot-cert-service/app/app.go
  example/controller-registration.yaml
  go.mod
  pkg/apis/service/v1alpha1/types.go
  pkg/apis/service/validation/validation.go
  pkg/apis/service/validation/validation_test.go
  pkg/client/scheme.go
  pkg/cmd/options.go
  pkg/controller/actuator.go
  pkg/controller/extension/actuator.go
  pkg/controller/extension/add.go
  pkg/controller/extension/assets/cert-dashboard.json
  pkg/controller/extension/assets/crd-cert.gardener.cloud_certificaterevocations.yaml
  pkg/controller/extension/assets/crd-cert.gardener.cloud_certificates.yaml
  pkg/controller/extension/assets/crd-cert.gardener.cloud_issuers.yaml
  pkg/controller/extension/assets/doc.go
  pkg/controller/extension/deployer.go
  pkg/controller/extension/deployer_gardenorseed.go
  pkg/controller/extension/deployer_issuers.go
  pkg/controller/extension/deployer_seed.go
  pkg/controller/extension/deployer_shoot.go
  pkg/controller/extension/deployer_test.go
  pkg/controller/extension/extension_suite_test.go
  pkg/controller/extension/model/issuer.go
  pkg/controller/extension/testassets/standard_seed.yaml
  pkg/controller/extension/testassets/standard_shoot.yaml
  pkg/controller/healthcheck/add.go
Labels: reviewed/ok-to-test, needs/ok-to-test, area/control-plane, kind/api-change, kind/enhancement, reviewed/lgtm, size/xl

#367 Update base image to `debian12`
  Dockerfile
Labels: reviewed/ok-to-test, needs/ok-to-test, area/control-plane, kind/enhancement, reviewed/lgtm, size/xs

#370 Add `OWNERS` and `OWNERS_ALIASES`
  OWNERS
  OWNERS_ALIASES
Labels: reviewed/ok-to-test, needs/ok-to-test, area/dev-productivity, kind/enhancement, reviewed/lgtm, size/xs

#374 renovate: enable dependency dashboard
  renovate.json
Labels: kind/task, size/XS, cla: yes, lgtm, approved, needs/ok-to-test, needs/review, reviewed/ok-to-test

#362 Remove RBAC wildcards from roles
  charts/gardener-extension-shoot-cert-service/templates/rbac.yaml
  example/controller-registration.yaml
  pkg/controller/extension/testassets/standard_seed.yaml
Labels: area/security, kind/enhancement, size/XS, cla: yes, lgtm, approved

#383 Drop redundant check step
  .ci/pipeline_definitions
  .ci/verify
Labels: area/dev-productivity, kind/task, size/S, ci/broken-pipeline-definition, cla: yes, lgtm, approved, needs/review, reviewed/ok-to-test

#388 Introduce generate-renovate-igore-deps.sh
  Makefile
  hack/generate-renovate-ignore-deps.sh
  renovate.json
  renovate.json5
Labels: area/dev-productivity, kind/enhancement, size/L, cla: yes, lgtm, approved, needs/review, reviewed/ok-to-test, needs/ok-to-test

#390 Fix pipeline
  .ci/pipeline_definitions
  .ci/verify
Labels: area/dev-productivity, kind/bug, size/S, cla: yes, lgtm, approved, needs/review, needs/ok-to-test

#380 Drop obsolete permissions
  charts/gardener-extension-shoot-cert-service/templates/rbac.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/cleanup, size/S, cla: yes, lgtm, approved, reviewed/ok-to-test

#393 chore: Retire Dependabot
  .github/dependabot.yaml
Labels: area/dev-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved, needs/review, needs/ok-to-test

#394 Allow `patch` of the `gardener-extension-heartbeat` lease
  charts/gardener-extension-shoot-cert-service/templates/rbac.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/task, size/XS, cla: yes, lgtm, approved, needs/review
