Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2025-03, with the labels that each got.

#354 Replaced shortcodes
  docs/tutorials/tutorial-custom-domain-with-istio.md
Labels: needs/ok-to-test, area/documentation, kind/enhancement, reviewed/lgtm, size/xs

#355 chore: Add copyright profile for GoLand
  .gitignore
  .idea/copyright/Gardener.xml
  .idea/copyright/profiles_settings.xml
Labels: reviewed/ok-to-test, needs/ok-to-test, area/dev-productivity, area/open-source, kind/enhancement, reviewed/lgtm, size/xs

#356 Restore Shoot Cert Service observability
  charts/internal/shoot-cert-management-seed/templates/configmap-dashboards.yaml
  charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml
  charts/internal/shoot-cert-management-seed/templates/prometheusrule.yaml
  charts/internal/shoot-cert-management-seed/templates/servicemonitor.yaml
Labels: needs/ok-to-test, area/monitoring, kind/bug, reviewed/lgtm, size/s
