Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2025-02, with the labels that each got.

#337 Support either ACME or CA as default issuer
  .gitignore
  charts/gardener-extension-shoot-cert-service/templates/_helpers.tpl
  charts/gardener-extension-shoot-cert-service/values.yaml
  charts/internal/shoot-cert-management-seed/templates/issuer.yaml
  example/controller-registration.yaml
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/validation/validation.go
  pkg/apis/config/validation/validation_test.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/controller/actuator.go
Labels: reviewed/ok-to-test, needs/ok-to-test, area/control-plane, kind/api-change, kind/enhancement, reviewed/lgtm, size/xl

#342 feat: Build `linux/arm64` image
  .ci/pipeline_definitions
Labels: needs/ok-to-test

#347 Remove `pkg/controller/config`
  pkg/cmd/options.go
  pkg/controller/add.go
  pkg/controller/config/config.go
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm

#351 Bump golang to 1.24 in CI/CD pipeline
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, needs/ok-to-test, kind/task, reviewed/lgtm, size/xs, area/compliance
