Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2025-06, with the labels that each got.

#410 Allow traffic to public/private networks to access virtual garden
  charts/gardener-extension-shoot-cert-service/templates/deployment.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/bug, size/XS, cla: yes, lgtm, approved, reviewed/ok-to-test

#415 Fix renovate.json5 and newly integrated e2e test
  example/extension-shoot-cert-service.yaml
  example/shoot-cert-service/base/kustomization.yaml
  hack/pebble-up.sh
  renovate.json5
Labels: area/quality, kind/task, size/S, cla: yes, lgtm, approved, reviewed/ok-to-test

#418 Update `resources` section of example operator extension
  docs/operations/deployment.md
Labels: area/documentation, kind/enhancement, size/S, cla: yes, lgtm, approved, reviewed/ok-to-test

#423 Remove `gardener/gardener-maintainers` from `CODEOWNERS` file
  CODEOWNERS
Labels: area/dev-productivity, kind/cleanup, size/XS, cla: yes, lgtm, approved
