Repository gardener/gardener-extension-shoot-cert-service, pull requests merged in 2025-09, with the labels that each got.

#460 Adjust required permissions for `upgrade-dependencies.yaml` workflow
  .github/workflows/upgrade-dependencies.yaml
Labels: kind/cleanup, size/XS, cla: yes, lgtm, approved, reviewed/ok-to-test

#458 Add validation of issuer secrets specified in shoot manifest
  go.mod
  go.sum
  pkg/controller/extension/shared/deployer_gardenorseed.go
  pkg/controller/extension/shared/deployer_issuers.go
  pkg/controller/extension/shared/deployer_seed.go
  pkg/controller/extension/shared/deployer_test.go
  renovate.json5
  test/integration/extension/reconcile_test.go
Labels: area/control-plane, kind/enhancement, size/L, cla: yes, lgtm, approved

#462 Overwrite default component-cli component prefixes
  .ocm/base-component.yaml
Labels: kind/task, size/XS, cla: yes, lgtm, approved

#465 Update build workflow to use Go 1.25 for verify step
  .github/workflows/build.yaml
Labels: kind/task, size/XS, cla: yes, lgtm, approved, reviewed/ok-to-test
